# Generated by Django 5.2.8 on 2026-03-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='total_bus',
            field=models.IntegerField(default=5),
        ),
    ]
