# Generated by Django 5.2.8 on 2026-03-09 20:30

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_userprofile_username_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=booking.models.generated_username, max_length=50, unique=True),
        ),
    ]
