# Generated by Django 5.2.8 on 2026-03-09 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_userprofile_userid_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.agency'),
        ),
    ]
