# Generated by Django 5.2.8 on 2026-03-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_bus_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
