# Generated by Django 5.2.8 on 2026-03-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_agency_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='booking.agency'),
        ),
    ]
