# Generated by Django 5.2.8 on 2026-03-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
