# Generated by Django 5.2.8 on 2026-03-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_route_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
