# Generated by Django 5.2.8 on 2026-03-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_route_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
