# Generated by Django 5.2.8 on 2026-03-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
